# Generated by Django 4.0.6 on 2022-07-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorsValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.PositiveBigIntegerField(default=0)),
                ('accX', models.FloatField(default=0)),
                ('accY', models.FloatField(default=0)),
                ('accZ', models.FloatField(default=0)),
                ('gyrX', models.FloatField(default=0)),
                ('gyrY', models.FloatField(default=0)),
                ('gyrZ', models.FloatField(default=0)),
            ],
        ),
    ]
