# Generated by Django 4.2.1 on 2023-06-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myimu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorsvalue',
            name='localtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
